title: TriHard lyrics
author: Leton German
email: neveraskedfor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Referencing the ambiguity of Mona Lisa’s smile, 
 this song finds Lil Wayne and Kendrick Lamar weaving a story of a deceptive woman who sets her “boyfriend” up for a robbery.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
